name: GitHub Metrics

on:
  # Schedule at 00:00 on every 3rd day-of-month, https://crontab.guru/#0_0_*/3_*_*
  schedule: [{ cron: "0 0 */3 * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on main
  push: { branches: ["main"] }

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set Current Year
        id: set-current-year
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
        run: |
          echo "Setting current year from: $(date), current system clock time: \n$(timedatectl)"
          echo "CURRENT_YEAR=$(date +'%Y')" >> "$GITHUB_OUTPUT"
      # https://github.com/lowlighter/metrics/blob/master/.github/readme/partials/documentation/setup/action.md
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: johnnymillergh
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/core/README.md#using-gists
          output_action: gist
          committer_gist: 18c656e56b86c137ed45ab71b9227ad6
          # committer_message: "chore($metrics): update GitHub metrics via GitHub Actions"
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/isocalendar/README.md
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/achievements/README.md
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/calendar/README.md
          plugin_calendar: yes
          plugin_calendar_limit: 3

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/habits/README.md
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/skyline/README.md
          plugin_skyline: yes
          plugin_skyline_year: ${{ steps.set-current-year.outputs.CURRENT_YEAR }}
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          # https://honzaap.github.io/GithubCity/?name=johnnymillergh&year=2023
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/topics/README.md
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/starlists/README.md
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: Awesome

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/activity/README.md
          plugin_activity: yes

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/wakatime/README.md
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/stars/README.md
          plugin_stars: yes
          plugin_stars_limit: 3

  build-github-pages:
    runs-on: ubuntu-latest
    needs: build-github-metrics
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
